import Head from "next/head";
import Image from "next/image";
import Board from "../../containers/Board";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tic-Tac-Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Board />
      </main>
    </div>
  );
}
